POST http://localhost:8000/api/csv/columns/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"; filename="1.csv"
Content-Type: text/csv

< ./production.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--